### ISSUE TITLE
CocoaPods support

### ISSUE THREAD

**Issue by agfa555** [omise/omise-ios#27]
I'm trying to update but I see that you are only supporting CocoaPods for v1.
Are you planning on releasing a pod anytime soon?
Normally every SDK has both options or only pods.

Thank you,

Andoni

**Comment by chakrit** [comment]
@agfa555 Hi, Thanks for the feedback!

Sorry, we don't have any plans for CocoaPods. We did not add support for v2 because the number of features has increased (and now we have to do weak linking with card.io) and maintaining all of them and trying to keep up with Xcode and Cocoapods changes (and how they clashes) at the same time is becoming a pain.

We actually have more dev capacity now and will see if someone can take over this, but don't keep your hopes up.

In the meantime, though, I'd suggest that there is nothing preventing you from using Carthage and CocoaPods at the same time. If you need integration help, feel free to pop over to our [gitter chat room](https://gitter.im/omise/omise-ios).

**Comment by agfa555** [comment]
@chakrit Hi, thanks for the fast reply!

Ok, I understand. I've always used pods cause they're so easy and implemented across the frameworks but I have always also wanted to give a try to Carthage. I have a big project going on and I'm alone so it might take me a bit. Can I still use the deprecated one for a while? When will you drop support for previous version?

Tanks a lot!

**Comment by chakrit** [comment]
@agfa555 We can support it for quite a while, but we're not actively working on it. All new features will be done in the new version only. So if you only need to do tokenization request then v1 should suffice.

**Comment by agfa555** [comment]
@chakrit OK, thanks!!!

**Comment by chakrit** [comment]
@agfa555 np! feel free to open more issues if you spot any bugs or have more questions!
