### ISSUE TITLE
CocoaPods Support

### ISSUE THREAD

**Issue by Jallynme** [omise/omise-ios#54]

**Comment by agfa555** [comment]
I tried this a while ago: https://github.com/omise/omise-ios/issues/27
Maybe we can help with the podspec?

Carthage + Cocoapods was a pain for me so I'm still using https://github.com/omise/omise-ios-swift but I think they recently deprecated it. 
You can try with this: pod 'Omise-iOS-Swift'
Maybe it'll work.
I only use for tokenizing, don't want any UI and I use card.io separately for different payment gateways.

Cheers.

**Comment by chakrit** [comment]
@Jallynme @agfa555 Sorry, our team has come to the conclusion that we will never support CocoaPods as we believe that its build system is based on a very flawed approach.

Playing catch-up with Apple and Xcode build tooling changes is not something we'd like to spend time doing every other Xcode release. Right now [`Carthage`](https://github.com/Carthage/Carthage) is the only method we'll be supporting since it's much less intrusive and we urge you to consider to use it as well.

Failing that, direct source clones should still works.
