### ISSUE TITLE
Installation hangs via Carthage

### ISSUE THREAD

**Issue by jonathanlu813** [omise/omise-ios#58]
Hi,

I was trying to integrate Omise iOS SDK into my project via Carthage, which is the only supported package manager by now, but failed. Here are some details:

- `carthage version`: 0.26.2
- `xcodebuild -version`: Xcode 9.1 Build version 9B55
- Are you using `--no-build`? no
- Are you using `--no-use-binaries`? no
- Are you using `--use-submodules`? no
- Are you using `--cache-builds`? no

After adding omise-ios to my Cartfile and run `carthage update`, the update process hangs after 
the line

`*** Checking out omise-ios at "v2.6.0"`

If I remove omise-ios and run again, it will go through to the build phase. 

I've worked around this issue by requesting Omise Token API by myself, so it's not urgent for me, but I think I should report this to you guys anyways.

**Comment by pitiphong-p** [comment]
Hi @jonathanlu813, thank you for reporting this bug. I have done some investigation and found something that may be the cause.

Since Omise for iOS SDK includes the `Card.io` feature which need to be built and bundled alongside with the Omise for iOS SDK, we added it as a git submodule dependency. This can cause the Carthage to fetch the `Card.io` repo which is a big git repository and could take a long time to fetch it. You can check if git is fetching the `Card.io` repo by running `ps` command which will show what `git` is doing.

Could you try again and please give it some more time to checkout this time.

**Comment by jonathanlu813** [comment]
Hi @pitiphong-p, I just checked with `ps | grep git` and found it was indeed cloning `Card.io`. I'll leave it there and go to bed now, and see if it can build successfully tomorrow morning. I'll keep you updated.

**Comment by jonathanlu813** [comment]
Confirmed it's related to cloning `Card.io`. Installation succeeded after I left it updating overnight.

**Comment by pitiphong-p** [comment]
Great!!! Thank you for reporting this and I would love to hear some feedback from you if you have.
