### ISSUE TITLE
How to create URL(Links API)?

### ISSUE THREAD

**Issue by son** [omise/omise-ios#66]
I want to use Pay Links.
How do I create a URL from an app?

**Comment by pitiphong-p** [comment]
Omise API doesn't support for creating a link with public key yet. So we can't provide that feature in our SDK.

My suggestion is to have your app call to your backend and have the backend call to Omise to create a link and return it to your app instead. This is the same flow as creating a charge from your app

**Comment by son** [comment]
@pitiphong-p 
Thank you for your reply.
All backends of my app are managed by Firebase, so there is no backend.
I am planning to use this API (https://www.omise.co/en/links-api) directly from the app, I would like to hear your opinion.

**Comment by chakrit** [comment]
@son We do not support such use case at the moment because there are numerous ways an end-user can tamper with the amount (paying for $1,000 worth of goods with just $1 charge, or altering the payee email) inside your app. So you will always need a validation logic of some kind on your backend.

The `skey` required to create links can also be used to perform other dangerous and sensitive actions on your behalf.

I've taken a look and it may be best to add something like [Cloud Functions](https://firebase.google.com/docs/functions/) to do this.
