### ISSUE TITLE
iOS Visa OTP page no cancel button

### ISSUE THREAD

**Issue by pauloec** [omise/omise-ios#87]
Hi!

The visa OTP page has no cancel button and so the user has no option to just close the page on iOS 12.2

presenter.present(handlerController, animated: true, completion: nil)

presenter is a UINavigationController and while in iOS 13 you have the option to slide down the page, the same doesn't happen on iOS 12. I do understand that not all OTP pages are the same and some contain the cancel button but that isn't the best approach IMO

**Comment by igroomgrim** [comment]
Hi @pauloec 
Thanks for your comment. We understand your point. Apple has a lot of changes in View Controller Presentation on iOS13 and because not all OTP pages are the same. You can provide a cancel or done button by yourself by programmatically in your OTP page on iOS12 like  
```
if #available(iOS 12, *) {
      navigationController.navigationItem.rightBarButtonItem = UIBarButtonItem(title: "Done", style: .done, target: self, action: #selector(dismissOTPPage))
}

@objc func dismissOTPPage() {
      self.dismiss(animated: true)
}
```
That would be support for iOS12 and the button will be hiding from iOS13. 
😄

**Comment by pauloec** [comment]
Hey @igroomgrim!

Yes, you're correct! I've done that before you've mentioned. I'm just concerned by the fact that the SDK could perhaps come ready outside of the box, if you know what i mean! This can lead to confusion, especially to small teams that are trying your product. I do understand that this will only happen while we're transitioning to iOS 13 though :)

Thanks for your feedback

**Comment by igroomgrim** [comment]
Hi @pauloec 
Thank you for your advice and support.
We'd love to hear your feedback that very useful for our SDK.
🙇
